export const START_FETCH_EMBED = 'START_FETCH_EMBED';
export const FETCH_EMBED_STARTED = 'FETCH_EMBED_STARTED';
export const FETCH_EMBED_COMPLETED = 'FETCH_EMBED_COMPLETED';
export const FETCH_EMBED_FAILED = 'FETCH_EMBED_FAILED';
